(ns clj-xref.core
  "Query API for clj-xref cross-reference databases.

   Typical usage:
     ;; Load a database generated by `lein xref` or `clj -T:xref generate`
     (def db (xref/load-db))

     ;; Query it
     (xref/who-calls db 'my.ns/my-fn)
     (xref/calls-who db 'my.ns/my-fn)
     (xref/who-references db 'my.ns/*config*)"
  (:require [clj-xref.emit :as emit]))

;; === Index building ===

(defn index
  "Add in-memory indexes to a flat xref database map.
   Call this on raw database maps (e.g., from EDN or from `analyze`)
   to enable queries."
  [db]
  (assoc db
         :vars-by-name (into {} (map (juxt :name identity)) (:vars db))
         :by-target    (group-by :to (:refs db))
         :by-source    (group-by :from (:refs db))
         :by-file      (group-by :file (:refs db))
         :ns-by-name   (into {} (map (juxt :name identity)) (:namespaces db))))

;; === Database construction ===

(defn load-db
  "Load an xref database from an EDN file and build in-memory indexes.
   Defaults to `.clj-xref/xref.edn` in the current directory."
  ([] (load-db ".clj-xref/xref.edn"))
  ([path] (-> (emit/read-edn path) index)))

(defn analyze
  "Run clj-kondo analysis on `paths` and return an indexed xref database.
   Requires clj-kondo on the classpath. Options are passed to
   `clj-xref.analyze/analyze`."
  [paths & [opts]]
  (let [analyze-fn (requiring-resolve 'clj-xref.analyze/analyze)]
    (-> (analyze-fn paths opts) index)))

(defn from-kondo-analysis
  "Build an indexed xref database from a pre-computed clj-kondo result
   (the return value of `clj-kondo.core/run!`)."
  [kondo-result & [{:keys [paths project]}]]
  (let [transform-fn (requiring-resolve 'clj-xref.analyze/transform-analysis)]
    (-> (transform-fn (:analysis kondo-result) {:paths (or paths []) :project project})
        index)))

;; === Core queries ===

(defn who-calls
  "Find all call sites of `sym`. Returns xref entries with :kind :call."
  [db sym]
  (filterv #(= :call (:kind %))
           (get (:by-target db) sym [])))

(defn calls-who
  "Find all vars called by `sym`. Returns xref entries with :kind :call."
  [db sym]
  (filterv #(= :call (:kind %))
           (get (:by-source db) sym [])))

(defn who-references
  "Find all references to `sym` (any kind: call, reference, macroexpand, etc.)."
  [db sym]
  (get (:by-target db) sym []))

(defn who-macroexpands
  "Find all macroexpansion sites of the macro `sym`."
  [db sym]
  (filterv #(= :macroexpand (:kind %))
           (get (:by-target db) sym [])))

(defn who-implements
  "Find all implementations of the protocol `sym`."
  [db sym]
  (filterv #(= :implement (:kind %))
           (get (:by-target db) sym [])))

(defn who-dispatches
  "Find all defmethod dispatch values for the multimethod `sym`."
  [db sym]
  (filterv #(= :dispatch (:kind %))
           (get (:by-target db) sym [])))

;; === Namespace queries ===

(defn ns-vars
  "List all var definitions in namespace `ns-sym`."
  [db ns-sym]
  (filterv #(= ns-sym (:ns %)) (:vars db)))

(defn ns-deps
  "Return the set of namespaces that `ns-sym` depends on
   (namespaces of vars referenced from `ns-sym`)."
  [db ns-sym]
  (let [ns-str (str ns-sym)]
    (->> (:refs db)
         (filter #(= ns-str (some-> (:from %) namespace)))
         (into #{} (comp (map :to)
                         (map namespace)
                         (remove nil?)
                         (remove #(= ns-str %))
                         (map symbol))))))

(defn ns-dependents
  "Return the set of namespaces that depend on `ns-sym`
   (namespaces containing references to vars in `ns-sym`)."
  [db ns-sym]
  (let [ns-str (str ns-sym)]
    (->> (:refs db)
         (filter #(= ns-str (some-> (:to %) namespace)))
         (into #{} (comp (map :from)
                         (map namespace)
                         (remove nil?)
                         (remove #(= ns-str %))
                         (map symbol))))))
